# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\git_E\studyLog\SoftwareArchitecture\proj\signUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 550)
        self.Register_page = QtWidgets.QWidget(Form)
        self.Register_page.setGeometry(QtCore.QRect(30, 30, 370, 480))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.Register_page.setFont(font)
        self.Register_page.setObjectName("Register_page")
        self.label = QtWidgets.QLabel(self.Register_page)
        self.label.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label.setStyleSheet("border-image: url(:/images/Egg.jpg);\n"
"border-radius:20px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Register_page)
        self.label_2.setGeometry(QtCore.QRect(40, 49, 280, 381))
        self.label_2.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border-radius:15px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Register_page)
        self.label_3.setGeometry(QtCore.QRect(110, 70, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(105, 118, 132);")
        self.label_3.setObjectName("label_3")
        self.loginButton = QtWidgets.QPushButton(self.Register_page)
        self.loginButton.setGeometry(QtCore.QRect(80, 270, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton#loginButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 255, 255, 100), stop: 1 rgba(255, 255, 255, 100));\n"
"    color: rgb(105, 118, 132, 150);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#loginButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 255, 255, 100), stop: 1 rgba(255, 255, 255, 226));\n"
"    color: rgba(131, 96, 53, 255); /* 호버 상태일 때의 글꼴 색상 변경 */\n"
"}\n"
"QPushButton#loginButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Register_page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 330, 201, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(105, 118, 132);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.signUpButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.signUpButton.setFont(font)
        self.signUpButton.setStyleSheet("QPushButton#signUpButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 255, 255, 50), stop: 1 rgba(255, 255, 255, 100));\n"
"    color: rgb(105, 118, 132, 150);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#signUpButton:hover {\n"
"    color: rgba(131, 96, 53, 255); /* 호버 상태일 때의 글꼴 색상 변경 */\n"
"}\n"
"\n"
"QPushButton#signUpButton:pressed {\n"
"    padding-left: 5px; /* 클릭 시 왼쪽 여백 추가 */\n"
"    padding-top: 5px; /* 클릭 시 위쪽 여백 추가 */\n"
"    color: rgba(91, 88, 53, 255); /* 클릭 시 글꼴 색상 변경 */\n"
"}")
        self.signUpButton.setObjectName("signUpButton")
        self.horizontalLayout.addWidget(self.signUpButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Register_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 130, 201, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(105, 118, 132);\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(105, 118, 132);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(32768)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color: rgb(105, 118, 132);\n"
"padding-bottom:7px;")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Sign Up"))
        self.loginButton.setText(_translate("Form", "Sign Up"))
        self.label_4.setText(_translate("Form", "Click to Log In"))
        self.signUpButton.setText(_translate("Form", "login"))
        self.lineEdit.setPlaceholderText(_translate("Form", " User Name"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", " Email"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", " Password"))
import res_rc
